### ISSUE TITLE
v0.12 not automerged

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/capella-console-client-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/capellaspace/console-client/blob/main/docs/pages/changelog.rst#0120-2024-01-04

appears to be stuck https://github.com/conda-forge/capella-console-client-feedstock/pull/15

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by grmpflh27** [comment]
hi @scottyhq 

I made sure `0.13.0` is available on conda-forge: https://anaconda.org/conda-forge/capella-console-client.

When trying to get 0.12.0 up I ran into some build issues (I believe something python 3.12 support releated) and honestly decided not too dig to deep by offering 0.13.0
